run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - bodyclose
    - noctx
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/chicogong/stream-relay-go

  misspell:
    locale: US

  gosec:
    excludes:
      - G104  # Audit errors not checked
      - G304  # File path provided as taint input

  prealloc:
    simple: true
    range-loops: true
    for-loops: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam

  max-issues-per-linter: 50
  max-same-issues: 10
